apiVersion: apps/v1
kind: Deployment
metadata:
  name: painel-admin
  namespace: default
  labels:
    app: painel-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: painel-admin
  template:
    metadata:
      labels:
        app: painel-admin
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: painel-admin
          image: registry.gitlab.com/jonataserpa/pock-microservice/painel-admin:latest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_URL
              value: "http://mock-server"
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.jonataserpa.com.br"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-publico
  namespace: default
  labels:
    app: portal-publico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-publico
  template:
    metadata:
      labels:
        app: portal-publico
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: portal-publico
          image: registry.gitlab.com/jonataserpa/pock-microservice/portal-publico:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_URL
              value: "http://mock-server"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-server
  namespace: default
  labels:
    app: mock-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-server
  template:
    metadata:
      labels:
        app: mock-server
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: mock-server
          image: registry.gitlab.com/jonataserpa/pock-microservice/mock-server:latest
          ports:
            - containerPort: 3001
          command: ["/bin/sh", "-c"]
          args:
            - |
              if [ ! -f /data/db.json ]; then
                cp /app/db.json /data/db.json;
              fi;
              json-server /data/db.json --port 3001 --host 0.0.0.0
          volumeMounts:
            - name: mock-data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: mock-data
          persistentVolumeClaim:
            claimName: mock-server-pvc
