apiVersion: v1
kind: Service
metadata:
  name: painel-admin
  namespace: default
spec:
  selector:
    app: painel-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portal-publico
  namespace: default
spec:
  selector:
    app: portal-publico
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mock-server
  namespace: default
spec:
  selector:
    app: mock-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
